AWSTemplateFormatVersion: "2010-09-09"
Description: AWS CloudFormation Template to deploy a simple website on EC2

Resources:
  # Security Group
  MySecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: Enable HTTP access on port 80
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: "80"
          ToPort: "80"
          CidrIp: 0.0.0.0/0

  # EC2 Instance
  MyEC2Instance:
    Type: AWS::EC2::Instance
    Properties:
      InstanceType: t2.micro
      SecurityGroups:
        - Ref: MySecurityGroup
      ImageId: ami-0c11a84584d4e09dd
      UserData:
        Fn::Base64: !Sub |
          #!/bin/bash
          yum update -y
          yum install -y httpd
          systemctl start httpd
          systemctl enable httpd
          echo "<h1>Welcome to my website</h1>" > /var/www/html/index.html

Outputs:
  WebsiteURL:
    Description: URL of the website
    Value:
      Fn::Sub: http://${MyEC2Instance.PublicDnsName}
