AWSTemplateFormatVersion: "2010-09-09"
Description: CloudFormation template to create an S3 bucket with a specified name

Parameters:
  BucketName:
    Description: The name of the S3 bucket
    Type: String
  AccessControl:
    Description: The access control settings for the S3 bucket
    Type: String
    Default: Private
    AllowedValues:
      - Private
      - PublicRead
      - PublicReadWrite
      - AuthenticatedRead
  VersioningStatus:
    Description: The versioning status for the S3 bucket
    Type: String
    Default: Enabled
    AllowedValues:
      - Enabled
      - Suspended
  LoggingBucketName:
    Description: The name of the S3 bucket where access logs are stored
    Type: String
    Default: ""
  LoggingPrefix:
    Description: The prefix for the access log files
    Type: String
    Default: ""
  LifecyclePrefix:
    Description: The prefix filter for lifecycle rules
    Type: String
    Default: ""
  LifecycleExpirationDays:
    Description: The number of days before objects are expired
    Type: Number
    Default: 365
  Environment:
    Description: The environment in which this bucket will be used
    Type: String
    Default: Production

Resources:
  MyS3Bucket:
    Type: "AWS::S3::Bucket"
    Properties:
      BucketName: !Ref BucketName
      AccessControl: !Ref AccessControl
      VersioningConfiguration:
        Status: !Ref VersioningStatus

      # Configure logging if LoggingBucketName is provided
      LoggingConfiguration:
        DestinationBucketName: !If
          - IsLoggingEnabled
          - !Ref LoggingBucketName
          - !Ref "AWS::NoValue"
        LogFilePrefix: !If
          - IsLoggingEnabled
          - !Ref LoggingPrefix
          - !Ref "AWS::NoValue"

      # Lifecycle rules configuration
      LifecycleConfiguration:
        Rules:
          - Id: ExpireObjectsRule
            Prefix: !Ref LifecyclePrefix
            Status: Enabled
            ExpirationInDays: !Ref LifecycleExpirationDays

      # Tags for the bucket
      Tags:
        - Key: Name
          Value: !Ref BucketName
        - Key: Environment
          Value: !Ref Environment

# Condition to check if logging is enabled
Conditions:
  IsLoggingEnabled: !Not [!Equals [!Ref LoggingBucketName, ""]]

Outputs:
  BucketName:
    Description: Name of the S3 bucket
    Value: !Ref MyS3Bucket
  BucketArn:
    Description: ARN of the S3 bucket
    Value: !GetAtt MyS3Bucket.Arn
  BucketDomainName:
    Description: Domain name of the S3 bucket
    Value: !GetAtt MyS3Bucket.DomainName
  BucketWebsiteURL:
    Description: Website URL of the S3 bucket (if static website hosting is enabled)
    Value: !GetAtt MyS3Bucket.WebsiteURL
  BucketRegionalDomainName:
    Description: The regional domain name of the S3 bucket
    Value: !GetAtt MyS3Bucket.RegionalDomainName
