AWSTemplateFormatVersion: "2010-09-09"
Description: CloudFormation template to create an S3 bucket with a specified name

Parameters:
  BucketName:
    Description: The name of the S3 bucket
    Type: String

Resources:
  MyS3Bucket:
    Type: "AWS::S3::Bucket"
    Properties:
      BucketName: !Ref BucketName
      AccessControl: Private
      VersioningConfiguration:
        Status: Enabled
      Tags:
        - Key: Name
          Value: !Ref BucketName
        - Key: Environment
          Value: Production

Outputs:
  BucketName:
    Description: Name of the S3 bucket
    Value: !Ref MyS3Bucket
  BucketArn:
    Description: ARN of the S3 bucket
    Value: !GetAtt MyS3Bucket.Arn
